[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  DATABASE_URL = "file:./dev.db"

[[plugins]]
  package = "@netlify/plugin-nextjs"